name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: RootDeveloperDS
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00F7FF&color_dots=#0d1117,#003333,#006666,#009999,#00CCCC
            dist/github-contribution-grid-snake.svg?color_snake=#0066FF&color_dots=#ebedf0,#c5e3ed,#79c7d9,#2fa3bc,#007b99

      - name: Push Snake Animation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
